<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_login();require_once __DIR__.'/../config/database.php';
$pdo=db();$erros=[];
if($_SERVER['REQUEST_METHOD']==='POST'){validate_csrf();$codigo=strtoupper(trim((string)($_POST['codigo']??'')));$setor=trim((string)($_POST['setor']??''));$tipo=(string)($_POST['tipo_vaga']??'GERAL');$obs=trim((string)($_POST['observacao']??''));if($codigo==='')$erros[]='Informe o código da vaga.';if($setor==='')$erros[]='Informe o setor.';if(!$erros){try{$stmt=$pdo->prepare('INSERT INTO vagas(codigo,setor,tipo_vaga,observacao) VALUES(?,?,?,?)');$stmt->execute([$codigo,$setor,$tipo,$obs?:null]);flash('sucesso','Vaga cadastrada.');redirect('vagas/index.php');}catch(PDOException $e){$erros[]=$e->getCode()==='23000'?'O código da vaga já está cadastrado.':'Não foi possível cadastrar a vaga.';}}}
$vagas=$pdo->query('SELECT * FROM vagas ORDER BY codigo')->fetchAll();$pageTitle='Vagas';require __DIR__.'/../includes/header.php';
?>
<div class="page-heading"><div><h1>Vagas</h1><p>Vagas disponíveis para o registro das entradas.</p></div></div><section class="form-panel"><h2>Nova vaga</h2><?php if($erros):?><ul class="error-list"><?php foreach($erros as $erro):?><li><?=e($erro)?></li><?php endforeach;?></ul><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="form-grid"><label>Código<input name="codigo" required maxlength="20"></label><label>Setor<input name="setor" required maxlength="80"></label><label>Tipo<select name="tipo_vaga"><?php foreach(['CARRO','MOTO','UTILITARIO','GERAL'] as $tipo):?><option><?=$tipo?></option><?php endforeach;?></select></label></div><label>Observação<textarea name="observacao" maxlength="255"></textarea></label><button class="button" type="submit">Cadastrar</button></form></section>
<h2>Vagas cadastradas</h2><div class="table-wrap"><table><thead><tr><th>Código</th><th>Setor</th><th>Tipo</th><th>Status</th></tr></thead><tbody><?php foreach($vagas as $v):?><tr><td><strong><?=e($v['codigo'])?></strong></td><td><?=e($v['setor'])?></td><td><?=e($v['tipo_vaga'])?></td><td><span class="badge badge-<?=strtolower($v['status'])?>"><?=e($v['status'])?></span></td></tr><?php endforeach;?></tbody></table></div>
<?php require __DIR__.'/../includes/footer.php';?>
