<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_login();require_once __DIR__.'/../config/database.php';
$pdo=db();$erros=[];$veiculos=$pdo->query("SELECT v.id_veiculo,v.placa,v.modelo,c.nome AS condutor FROM veiculos v JOIN condutores c ON c.id_condutor=v.id_condutor WHERE v.status='ATIVO' AND c.status='ATIVO' ORDER BY v.placa")->fetchAll();$vagas=$pdo->query("SELECT id_vaga,codigo,setor FROM vagas WHERE status='LIVRE' ORDER BY codigo")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){validate_csrf();$idVeiculo=filter_input(INPUT_POST,'id_veiculo',FILTER_VALIDATE_INT)?:0;$idVaga=filter_input(INPUT_POST,'id_vaga',FILTER_VALIDATE_INT)?:0;$motivo=trim((string)($_POST['motivo_visita']??''));$obs=trim((string)($_POST['observacao']??''));if(!$idVeiculo)$erros[]='Selecione um veículo.';if(!$idVaga)$erros[]='Selecione uma vaga livre.';
 if(!$erros){try{$pdo->beginTransaction();$stmt=$pdo->prepare("SELECT id_movimentacao FROM movimentacoes WHERE id_veiculo=? AND status='ABERTA' FOR UPDATE");$stmt->execute([$idVeiculo]);if($stmt->fetch())throw new DomainException('Este veículo já possui uma entrada aberta.');$stmt=$pdo->prepare("SELECT status FROM vagas WHERE id_vaga=? FOR UPDATE");$stmt->execute([$idVaga]);if($stmt->fetchColumn()!=='LIVRE')throw new DomainException('A vaga selecionada não está mais livre.');$stmt=$pdo->prepare('SELECT id_condutor FROM veiculos WHERE id_veiculo=? AND status=\'ATIVO\'');$stmt->execute([$idVeiculo]);$idCondutor=(int)$stmt->fetchColumn();if(!$idCondutor)throw new DomainException('O veículo selecionado não está disponível.');$stmt=$pdo->prepare('INSERT INTO movimentacoes(id_veiculo,id_condutor,id_vaga,id_usuario_entrada,motivo_visita,observacao) VALUES(?,?,?,?,?,?)');$stmt->execute([$idVeiculo,$idCondutor,$idVaga,current_user_id(),$motivo?:null,$obs?:null]);$pdo->prepare("UPDATE vagas SET status='OCUPADA' WHERE id_vaga=?")->execute([$idVaga]);$pdo->commit();flash('sucesso','Entrada registrada.');redirect('movimentacoes/index.php');}catch(DomainException $e){if($pdo->inTransaction())$pdo->rollBack();$erros[]=$e->getMessage();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$erros[]='Não foi possível registrar a entrada.';}}
}
$pageTitle='Registrar entrada';require __DIR__.'/../includes/header.php';
?>
<section class="form-panel"><h1>Registrar entrada</h1><?php if($erros):?><ul class="error-list"><?php foreach($erros as $erro):?><li><?=e($erro)?></li><?php endforeach;?></ul><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><label>Veículo<select name="id_veiculo" required><option value="">Selecione</option><?php foreach($veiculos as $v):?><option value="<?=(int)$v['id_veiculo']?>" <?=(int)($_POST['id_veiculo']??0)===(int)$v['id_veiculo']?'selected':''?>><?=e($v['placa'].' — '.$v['modelo'].' — '.$v['condutor'])?></option><?php endforeach;?></select></label><label>Vaga<select name="id_vaga" required><option value="">Selecione</option><?php foreach($vagas as $v):?><option value="<?=(int)$v['id_vaga']?>" <?=(int)($_POST['id_vaga']??0)===(int)$v['id_vaga']?'selected':''?>><?=e($v['codigo'].' — '.$v['setor'])?></option><?php endforeach;?></select></label><label>Motivo da visita<input name="motivo_visita" maxlength="150" value="<?=e($_POST['motivo_visita']??'')?>"></label><label>Observação<textarea name="observacao" maxlength="255"><?=e($_POST['observacao']??'')?></textarea></label><div class="form-actions"><button class="button" type="submit">Confirmar entrada</button><a class="button button-light" href="index.php">Cancelar</a></div></form></section>
<?php require __DIR__.'/../includes/footer.php';?>
