<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_login();require_once __DIR__.'/../config/database.php';
$pdo=db();$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT)?:0;$stmt=$pdo->prepare("SELECT m.*,v.placa,v.modelo,c.nome AS condutor,vg.codigo AS vaga FROM movimentacoes m JOIN veiculos v ON v.id_veiculo=m.id_veiculo JOIN condutores c ON c.id_condutor=m.id_condutor JOIN vagas vg ON vg.id_vaga=m.id_vaga WHERE m.id_movimentacao=?");$stmt->execute([$id]);$m=$stmt->fetch();if(!$m){flash('erro','Movimentação não encontrada.');redirect('movimentacoes/index.php');}
$erro='';if($_SERVER['REQUEST_METHOD']==='POST'){validate_csrf();try{$pdo->beginTransaction();$stmt=$pdo->prepare("SELECT id_vaga,status FROM movimentacoes WHERE id_movimentacao=? FOR UPDATE");$stmt->execute([$id]);$atual=$stmt->fetch();if(!$atual||$atual['status']!=='ABERTA')throw new DomainException('Esta movimentação não possui entrada aberta.');$stmt=$pdo->prepare("UPDATE movimentacoes SET data_hora_saida=NOW(),id_usuario_saida=?,status='FINALIZADA' WHERE id_movimentacao=?");$stmt->execute([current_user_id(),$id]);$pdo->prepare("UPDATE vagas SET status='LIVRE' WHERE id_vaga=?")->execute([$atual['id_vaga']]);$pdo->commit();flash('sucesso','Saída registrada.');redirect('movimentacoes/index.php');}catch(DomainException $e){if($pdo->inTransaction())$pdo->rollBack();$erro=$e->getMessage();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$erro='Não foi possível registrar a saída.';}}
$pageTitle='Registrar saída';require __DIR__.'/../includes/header.php';
?>
<section class="form-panel"><h1>Registrar saída</h1><?php if($erro):?><div class="alert alert-erro"><?=e($erro)?></div><?php endif;?><?php if($m['status']!=='ABERTA'):?><div class="alert alert-erro">Esta movimentação já foi finalizada.</div><?php endif;?><div class="details"><dl><dt>Veículo</dt><dd><?=e($m['placa'].' — '.$m['modelo'])?></dd><dt>Condutor</dt><dd><?=e($m['condutor'])?></dd><dt>Vaga</dt><dd><?=e($m['vaga'])?></dd><dt>Entrada</dt><dd><?=e(date('d/m/Y H:i',strtotime($m['data_hora_entrada'])))?></dd></dl></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><div class="form-actions"><button class="button button-secondary" type="submit" <?=$m['status']!=='ABERTA'?'disabled':''?>>Confirmar saída</button><a class="button button-light" href="index.php">Cancelar</a></div></form></section>
<?php require __DIR__.'/../includes/footer.php';?>
