<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_login();require_once __DIR__.'/../config/database.php';
$placa=normalize_plate((string)($_GET['placa']??''));$termo=trim((string)($_GET['termo']??''));$inicio=trim((string)($_GET['inicio']??''));$fim=trim((string)($_GET['fim']??''));$tipo=(string)($_GET['tipo']??'');$where=[];$params=[];
if($placa!==''){$where[]='v.placa LIKE :placa';$params['placa']='%'.$placa.'%';}if($termo!==''){$where[]='(v.modelo LIKE :termo OR c.nome LIKE :termo)';$params['termo']='%'.$termo.'%';}if($inicio!==''){$where[]='m.data_hora_entrada >= :inicio';$params['inicio']=$inicio.' 00:00:00';}if($fim!==''){$where[]='m.data_hora_entrada <= :fim';$params['fim']=$fim.' 23:59:59';}if($tipo==='ENTRADA')$where[]='m.status IN (\'ABERTA\',\'FINALIZADA\')';if($tipo==='SAIDA')$where[]="m.status='FINALIZADA'";if($tipo==='PRESENTE')$where[]="m.status='ABERTA'";
$sql="SELECT m.*,v.placa,v.modelo,c.nome AS condutor,vg.codigo AS vaga FROM movimentacoes m JOIN veiculos v ON v.id_veiculo=m.id_veiculo JOIN condutores c ON c.id_condutor=m.id_condutor JOIN vagas vg ON vg.id_vaga=m.id_vaga".($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY m.data_hora_entrada DESC';$stmt=db()->prepare($sql);$stmt->execute($params);$resultados=$stmt->fetchAll();$pageTitle='Consulta de movimentações';require __DIR__.'/../includes/header.php';
?>
<div class="page-heading"><div><h1>Consulta de movimentações</h1><p>Pesquise por placa, veículo, condutor, período ou situação.</p></div></div><form class="filters" method="get"><div class="form-grid"><label>Placa<input name="placa" maxlength="8" value="<?=e($placa)?>"></label><label>Veículo ou condutor<input name="termo" value="<?=e($termo)?>"></label><label>Data inicial<input type="date" name="inicio" value="<?=e($inicio)?>"></label><label>Data final<input type="date" name="fim" value="<?=e($fim)?>"></label><label>Tipo<select name="tipo"><option value="">Todos</option><option value="ENTRADA" <?=$tipo==='ENTRADA'?'selected':''?>>Entradas</option><option value="SAIDA" <?=$tipo==='SAIDA'?'selected':''?>>Saídas</option><option value="PRESENTE" <?=$tipo==='PRESENTE'?'selected':''?>>Presentes</option></select></label></div><div class="action-row"><button class="button" type="submit">Aplicar filtros</button><a class="button button-light" href="index.php">Limpar filtros</a></div></form>
<?php if(!$resultados):?><p class="empty-state">Nenhum resultado encontrado para os filtros informados.</p><?php else:?><p><strong><?=count($resultados)?></strong> registro(s) encontrado(s).</p><div class="table-wrap"><table><thead><tr><th>Placa</th><th>Veículo</th><th>Condutor</th><th>Vaga</th><th>Entrada</th><th>Saída</th><th>Status</th></tr></thead><tbody><?php foreach($resultados as $m):?><tr><td><?=e($m['placa'])?></td><td><?=e($m['modelo'])?></td><td><?=e($m['condutor'])?></td><td><?=e($m['vaga'])?></td><td class="nowrap"><?=e(date('d/m/Y H:i',strtotime($m['data_hora_entrada'])))?></td><td class="nowrap"><?=e($m['data_hora_saida']?date('d/m/Y H:i',strtotime($m['data_hora_saida'])):'—')?></td><td><?=e($m['status'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php require __DIR__.'/../includes/footer.php';?>
